# This is a basic workflow to help you get started with Actions

name: Demo Basic workflow

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "testConcurency" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    inputs:
      name: 
        description: "person to greet"
        default: "world"
        required: true

concurrency:
  group: build and test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test-on-pr:
    name: Build and Test on Pull Request
    runs-on: ubuntu-latest
    steps:
      - Build the Code
      run |
        echo "Starting Code Build"
        sleep 5m
        echo "Finish Code Build"

  greet:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python: [3.8]
    runs-on: ${{ matrix.os }}
    

    steps: 
      - name: Send greeting and Run scripts
        run: |

          echo "Hello ${{ github.event.input.name }}"
          echo "Python ver ${{ matrix.python }}"
          

  # This workflow contains a single job called "build"
  Dev build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "I am Runing a job in the Dev Env"

  QA build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "I am Runing a job in the QA Env"
  
  PROD build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "I am Runing a job in the PROD Env"
  
